In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('trips_with_frequencies.csv')
df['trip_capacity'] = 676

In [4]:
df.to_csv('trips_with_frequencies.csv')

In [5]:
df = pd.read_csv('trips_with_frequencies.csv')
df['trip_cap_per_year'] = 676 * df['adjusted_days_per_year']
df['trip_passengers_transporter_per_year'] = 206 * df['adjusted_days_per_year']
df.to_csv('trips_with_frequencies.csv')

In [1]:
import pandas as pd

# ✅ Create dummy Flights dataset
flights_data = pd.DataFrame([
    {"dep_city": "Berlin", "des_city": "Munich", "Distance": 500, "Total Passengers Transported": 300,
     "OriginLat": 52.52, "OriginLong": 13.405, "DestLat": 48.1351, "DestLong": 11.582},
    {"dep_city": "Frankfurt", "des_city": "Hamburg", "Distance": 400, "Total Passengers Transported": 250,
     "OriginLat": 50.1109, "OriginLong": 8.6821, "DestLat": 53.5511, "DestLong": 9.9937},
    {"dep_city": "Cologne", "des_city": "Stuttgart", "Distance": 350, "Total Passengers Transported": 200,
     "OriginLat": 50.9375, "OriginLong": 6.9603, "DestLat": 48.7758, "DestLong": 9.1829},
    {"dep_city": "Dusseldorf", "des_city": "Leipzig", "Distance": 450, "Total Passengers Transported": 220,
     "OriginLat": 51.2277, "OriginLong": 6.7735, "DestLat": 51.3397, "DestLong": 12.3731},
    {"dep_city": "Dortmund", "des_city": "Bremen", "Distance": 300, "Total Passengers Transported": 180,
     "OriginLat": 51.5136, "OriginLong": 7.4653, "DestLat": 53.0793, "DestLong": 8.8017}
])

# ✅ Create dummy Trains dataset
trains_data = pd.DataFrame([
    {"stop_name": "Berlin", "next_stop_name": "Leipzig", "trip_count": 3, "total_passengers": 1500, "capacity": 500,
     "OriginLat": 52.52, "OriginLong": 13.405, "DestLat": 51.3397, "DestLong": 12.3731},
    {"stop_name": "Leipzig", "next_stop_name": "Munich", "trip_count": 3, "total_passengers": 1400, "capacity": 480,
     "OriginLat": 51.3397, "OriginLong": 12.3731, "DestLat": 48.1351, "DestLong": 11.582},
    {"stop_name": "Frankfurt", "next_stop_name": "Hamburg", "trip_count": 4, "total_passengers": 1600, "capacity": 550,
     "OriginLat": 50.1109, "OriginLong": 8.6821, "DestLat": 53.5511, "DestLong": 9.9937},
    {"stop_name": "Cologne", "next_stop_name": "Stuttgart", "trip_count": 3, "total_passengers": 1300, "capacity": 450,
     "OriginLat": 50.9375, "OriginLong": 6.9603, "DestLat": 48.7758, "DestLong": 9.1829},
    {"stop_name": "Dusseldorf", "next_stop_name": "Leipzig", "trip_count": 2, "total_passengers": 1100, "capacity": 400,
     "OriginLat": 51.2277, "OriginLong": 6.7735, "DestLat": 51.3397, "DestLong": 12.3731}
])

# ✅ Create dummy Train Trips dataset
train_trips_data = pd.DataFrame([
    {"trip_id": "T1", "stop_name": "Berlin", "next_stop_name": "Leipzig", "stop_sequence": 0, "trip_capacity": 500},
    {"trip_id": "T1", "stop_name": "Leipzig", "next_stop_name": "Munich", "stop_sequence": 1, "trip_capacity": 500},
    {"trip_id": "T2", "stop_name": "Frankfurt", "next_stop_name": "Hamburg", "stop_sequence": 0, "trip_capacity": 550},
    {"trip_id": "T3", "stop_name": "Cologne", "next_stop_name": "Stuttgart", "stop_sequence": 0, "trip_capacity": 450},
    {"trip_id": "T4", "stop_name": "Dusseldorf", "next_stop_name": "Leipzig", "stop_sequence": 0, "trip_capacity": 400},
    {"trip_id": "T5", "stop_name": "Dortmund", "next_stop_name": "Bremen", "stop_sequence": 0, "trip_capacity": 300},
    {"trip_id": "T6", "stop_name": "Berlin", "next_stop_name": "Hamburg", "stop_sequence": 0, "trip_capacity": 480},
    {"trip_id": "T6", "stop_name": "Hamburg", "next_stop_name": "Munich", "stop_sequence": 1, "trip_capacity": 480},
    {"trip_id": "T7", "stop_name": "Frankfurt", "next_stop_name": "Stuttgart", "stop_sequence": 0, "trip_capacity": 500},
    {"trip_id": "T8", "stop_name": "Leipzig", "next_stop_name": "Bremen", "stop_sequence": 0, "trip_capacity": 320}
])

# ✅ Save as CSV files
flights_path = "./dummy_flights.csv"
trains_path = "./dummy_trains.csv"
train_trips_path = "./dummy_train_trips.csv"

flights_data.to_csv(flights_path, index=False)
trains_data.to_csv(trains_path, index=False)
train_trips_data.to_csv(train_trips_path, index=False)

# Return file paths for user to download
flights_path, trains_path, train_trips_path

('./dummy_flights.csv', './dummy_trains.csv', './dummy_train_trips.csv')

In [6]:
df = pd.read_csv('trips_with_frequencies.csv')
df.head()

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,trip_id,stop_id,stop_sequence,stop_name,...,DestLon,route_id,service_id,adjusted_days_per_year,stop_city,next_stop_city,capacity,trip_capacity,trip_cap_per_year,trip_passengers_transporter_per_year
0,0,0,0,0,0,0,245,546652,0,Singen(Hohentwiel),...,8.772597,79.0,19.0,260.0,Friedrichshafen,Friedrichshafen,206,676,175760.0,53560.0
1,1,1,1,1,1,1,245,642362,1,Engen,...,8.798271,79.0,19.0,260.0,Friedrichshafen,Friedrichshafen,206,676,175760.0,53560.0
2,2,2,2,2,2,2,245,210691,2,Tuttlingen,...,8.741704,79.0,19.0,260.0,Friedrichshafen,Friedrichshafen,206,676,175760.0,53560.0
3,3,3,3,3,3,3,245,614011,3,Spaichingen,...,8.639871,79.0,19.0,260.0,Friedrichshafen,Stuttgart,206,676,175760.0,53560.0
4,4,4,4,4,4,4,245,472515,4,Rottweil,...,8.575479,79.0,19.0,260.0,Stuttgart,Stuttgart,206,676,175760.0,53560.0

In [8]:
df.drop(columns=['Unnamed: 0.5','Unnamed: 0.4','Unnamed: 0.3','Unnamed: 0.2','Unnamed: 0.1'],inplace=True)

In [9]:
df.head()

,Unnamed: 0,trip_id,stop_id,stop_sequence,stop_name,route_short_name,next_stop_id,next_stop_name,totalTripTime,osm_distance,...,DestLon,route_id,service_id,adjusted_days_per_year,stop_city,next_stop_city,capacity,trip_capacity,trip_cap_per_year,trip_passengers_transporter_per_year
0,0,245,546652,0,Singen(Hohentwiel),IC 87,642362.0,Engen,118.0,14.173633,...,8.772597,79.0,19.0,260.0,Friedrichshafen,Friedrichshafen,206,676,175760.0,53560.0
1,1,245,642362,1,Engen,IC 87,210691.0,Tuttlingen,118.0,19.667646,...,8.798271,79.0,19.0,260.0,Friedrichshafen,Friedrichshafen,206,676,175760.0,53560.0
2,2,245,210691,2,Tuttlingen,IC 87,614011.0,Spaichingen,118.0,12.302953,...,8.741704,79.0,19.0,260.0,Friedrichshafen,Friedrichshafen,206,676,175760.0,53560.0
3,3,245,614011,3,Spaichingen,IC 87,472515.0,Rottweil,118.0,15.489908,...,8.639871,79.0,19.0,260.0,Friedrichshafen,Stuttgart,206,676,175760.0,53560.0
4,4,245,472515,4,Rottweil,IC 87,15537.0,Oberndorf(Neckar),118.0,17.592425,...,8.575479,79.0,19.0,260.0,Stuttgart,Stuttgart,206,676,175760.0,53560.0

In [11]:
df.drop(columns=['Unnamed: 0'],inplace=True)
df['Emissions_Per_trip'] = df['capacity']*df['osm_distance']*41

In [12]:
df['Emissions_Per_trip'].describe()

count    4.040000e+04
mean     4.604438e+05
std      4.228859e+05
min      3.941732e+03
25%      1.501627e+05
50%      3.371617e+05
75%      6.602639e+05
max      4.427337e+06
Name: Emissions_Per_trip, dtype: float64

In [13]:
df.to_csv('trips_with_frequencies.csv')